### ISSUE TITLE
Crash, even when alone.

### ISSUE THREAD

**Issue by WolfSteelpaw** [AzureDoom/AzureDoom-Doom-Fabric#1]
Every time I try to run your mod, even alone, it automatically crashes Minecraft.

**Comment by AzureDoom** [comment]
No log no help

**Comment by WolfSteelpaw** [comment]
But I didn't receive a log from minecraft

**Comment by AzureDoom** [comment]
There is always a log

**Comment by WolfSteelpaw** [comment]
Well, idk how to view it then

**Comment by WolfSteelpaw** [comment]
nvm, just looked, log:[14:56:33] [main/WARN]: Error loading class: top/theillusivec4/curios/api/CuriosApi (java.lang.ClassNotFoundException: top/theillusivec4/curios/api/CuriosApi)

**Comment by WolfSteelpaw** [comment]
does the doom mod have any dependencies?
