### ISSUE TITLE
Leaping Enchant Issue

### ISSUE THREAD

**Issue by Lanos** [AzureDoom/AzureDoom-Doom-Fabric#14]
The Issue arises when generating loot it seems. I use Draylar's Battle Towers and Repurposed Structures (Fabric) with this mod. It looks like anything that generates enchated items/books through the loot tables for these mods will in some way mess with the Leaping Enchant. My allocated memory will cap, and then I will crash.

This is the only error I get (repeating over and over):

`
java.lang.StackOverflowError
    at mod.azure.doom.enchantments.LeapingDoomEnchantment.getMinPower(LeapingDoomEnchantment.java:26)
`

**Comment by AzureDoom** [comment]
Should be fixed in the next update

**Comment by Lanos** [comment]
Cheers mate, appreciate the quick response. I've edited the loot tables to remove the enchanted stuff for now, and it works fine.
