### ISSUE TITLE
[1.16.5] Client Crash when Viewing Recipe for Argent Energy

### ISSUE THREAD

**Issue by HockeyZman2000** [AzureDoom/AzureDoom-Doom-Fabric#15]
Attempting to view the recipe for Argent Energy in Roughly Enough Items crashes the client.

Crash Report: https://pastebin.pl/view/13d8b8af

Any help would be greatly appreciated!

**Comment by HockeyZman2000** [comment]
Update: also appears to crash when attempting to view Entity Loot Drops with Roughly Enough Resources installed. Same crash report but with Shotgun Guy as the rendered entity instead of Imp

**Comment by AzureDoom** [comment]
This issue seems to an issue with Geckolib and REI. It would be on REI to fix, please let them know as well.

**Comment by HockeyZman2000** [comment]
I did. Thanks for the info! Hopefully it'll get fixed as they updated it like 4 hours ago.

**Comment by AzureDoom** [comment]
actually just noticed on your REI items, you are using a SUPER old geckolib version. You should update that.

**Comment by HockeyZman2000** [comment]
Okay will do. That version of geckolib was embedded in with one of the other mods, so I'm downloading the newest version seperately right now.

**Comment by HockeyZman2000** [comment]
That actually fixed the issue, and a couple others that we had been having! Thanks so much for noticing that!
