### ISSUE TITLE
Guns cannot be shot in survival mode even with ammo in the inventory

### ISSUE THREAD

**Issue by HockeyZman2000** [AzureDoom/AzureDoom-Doom-Fabric#16]
Cannot shoot the chaingun or any other gun in survival mode, even with ammo. Still works in creative mode

**Comment by AzureDoom** [comment]
Which version?

**Comment by HockeyZman2000** [comment]
I was just on 3.9.4. Does it happen to be fixed in the newest version? It didn't say anything about it in the changelog

**Comment by AzureDoom** [comment]
Please test latest

**Comment by HockeyZman2000** [comment]
Still does not work, tested with latest version

**Comment by AzureDoom** [comment]
Fixed in releasing coming in about 20 minutes
