### ISSUE TITLE
[Error] Ticking Player on Server after holding Chainsaw 64

### ISSUE THREAD

**Issue by HockeyZman2000** [AzureDoom/AzureDoom-Doom-Fabric#17]
When trying to test out my other issue, I came across this one. Yay! Basically after getting the Chainsaw 64 item out of REI and putting it in my inventory, I immediately get disconnected from the server with a "ticking entity" error.

Server Log: https://pastebin.com/FG9QDZz8

**Comment by HockeyZman2000** [comment]
Tested this with the latest version: 3.9.5

**Comment by AzureDoom** [comment]
Fixed in upcoming release
