### ISSUE TITLE
[1.16.5 - Fabric] Performance Issues

### ISSUE THREAD

**Issue by FroggoRibbit** [AzureDoom/AzureDoom-Doom-Fabric#19]
Not too certain on why, but I am experiencing huge performance cuts with the fabric variant of the mod installed. With no other modifications installed, I typically receive about 300-400fps (that being only the fabric client). However, when MCDoom is installed alongside the required dependencies, that being Geckolib and Curios API, it drops tremendously. Currently I have the latest versions of those previously mentioned mods. Even with performance enhancing mods such as Sodium, Phosphor, and Lithium, I still gets massive drops in frames.

![2021-02-20_14 55 43](https://user-images.githubusercontent.com/79379450/108607325-a32ab480-738d-11eb-8ea6-91ee2c04f6db.png)
^^^ This is just with fabric and no other mods.

![2021-02-20_14 58 56](https://user-images.githubusercontent.com/79379450/108607333-b5a4ee00-738d-11eb-97ac-d5ecaccec6a6.png)
^^^ This is with MCDoom, Geckolib, and Curios API only.

I may be the only one having this issue, but I just want to be certain about that assumption. I am willing to post a video if requested. Thank you for reading!

**Comment by AzureDoom** [comment]
This is on the Geckolib side of things and is something that is in middle of development for so for now, there is nothing to be done. We have a few road blocks to fix before we can release new system.

**Comment by FroggoRibbit** [comment]
> 
> 
> This is on the Geckolib side of things and is something that is in middle of development for so for now, there is nothing to be done. We have a few road blocks to fix before we can release new system.

Thank you for responding quickly! Hope to see further development on the mod. I honestly really enjoy it.
