### ISSUE TITLE
doom:marauder 

### ISSUE THREAD

**Issue by skitzozombie25** [AzureDoom/AzureDoom-Doom-Fabric#2]
-- Entity being ticked --
Details:
	Entity Type: doom:marauder (mod.azure.doom.entity.MarauderEntity)
	Entity ID: 335
	Entity Name: Yeeter Sprinter Withering Marauder
	Entity's Exact location: 77.85, 33.00, -19.39
	Entity's Block location: World: (77,33,-20), Chunk: (at 13,2,12 in 4,-2; contains blocks 64,0,-32 to 79,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:406)

**Comment by AzureDoom** [comment]
`Entity Name: Yeeter Sprinter Withering Marauder`
You are using a mod that messes with the mob. Without a full log, I can't fix or support this.
