### ISSUE TITLE
Wither Skull Projectile Crash

### ISSUE THREAD

**Issue by ChrisLensFlare** [AzureDoom/AzureDoom-Doom-Fabric#21]
When fighting the Wither, I used both the Plasma Gun and the Chaingun. When those weapons' projectiles collided with the Wither Skull Projectile, the game crashed.
Untested with other projectiles from the mod.

[crash-2021-03-11_14.23.03-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6125781/crash-2021-03-11_14.23.03-server.txt)
[crash-2021-03-11_14.13.43-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6125729/crash-2021-03-11_14.13.43-server.txt)
[crash-2021-03-11_14.06.17-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6125719/crash-2021-03-11_14.06.17-server.txt)
[crash-2021-03-11_14.03.04-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6125720/crash-2021-03-11_14.03.04-server.txt)
[crash-2021-03-11_13.58.47-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6125721/crash-2021-03-11_13.58.47-server.txt)
[crash-2021-03-11_13.54.08-server.txt](https://github.com/AzureDoom/AzureDoom-Doom-Mod/files/6125722/crash-2021-03-11_13.54.08-server.txt)

**Comment by AzureDoom** [comment]
Please use the Fabric repo for the fabric version.
