### ISSUE TITLE
Weird issue preventing saving and loading of chunks

### ISSUE THREAD

**Issue by MechanosG** [AzureDoom/AzureDoom-Doom-Fabric#23]
Dunno how else to describe it.  It's pretty severe, and the error in console didn't give me any hints.  I had to do the 50/50 method to find out MCDoom was causing it.  1.16.5 with 0.11.3 Fabric, using MC Doom 3.10.0.  No crash log, but I'll add the bloated normal log.

[latest.log](https://github.com/AzureDoom/AzureDoom-Doom-Fabric/files/6347827/latest.log)

**Comment by AzureDoom** [comment]
Resolved in next update already

**Comment by Rubyz67** [comment]
so when is the next update?

**Comment by AzureDoom** [comment]
No ETA at this time as I'm in the process of doing a major overall of the mod and adding new things.

**Comment by AzureDoom** [comment]
ETA of hopefully end of month, this is a massive update, hence why it took so long

**Comment by AzureDoom** [comment]
Closing as fixed in latest Beta
