### ISSUE TITLE
Firing the BFG (9000 & Eternal) at a group of mobs crashes the game. (Fabric 1.16.5)

### ISSUE THREAD

**Issue by misternman** [AzureDoom/AzureDoom-Doom-Fabric#24]
When I fire the BFGs at a group of 5 mobs and above, the game crashes.
The only mod installed was MCDoom along side the dependencies.
I'll attach the crash report along side this post.

[crash-2021-04-26_22.50.48-client.txt](https://github.com/AzureDoom/AzureDoom-Doom-Fabric/files/6380224/crash-2021-04-26_22.50.48-client.txt)

**Comment by AzureDoom** [comment]
should be fixed in upcoming update. No ETA currently.

**Comment by AzureDoom** [comment]
ETA of hopefully end of month, this is a massive update, hence why it took so long

**Comment by AzureDoom** [comment]
Closing as fixed in latest Beta
