### ISSUE TITLE
Crash when ticking Cyberdemon 2016

### ISSUE THREAD

**Issue by ChrisLensFlare** [AzureDoom/AzureDoom-Doom-Fabric#27]
https://pastebin.com/UJQEZ272

**Comment by AzureDoom** [comment]
Will be fixed in updated, not ETA

**Comment by AzureDoom** [comment]
whoops didn't mean to close it, just pushed the fix to the github, update is not ready for release yet.

**Comment by AzureDoom** [comment]
ETA of hopefully end of month, this is a massive update, hence why it took so long

**Comment by AzureDoom** [comment]
Closing as fixed in latest Beta
