### ISSUE TITLE
Player crashing from missing model [1.17.1] latest mod

### ISSUE THREAD

**Issue by red2blue** [AzureDoom/AzureDoom-Doom-Fabric#28]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 7/22/21, 1:56 PM
Description: Rendering entity in world

software.bernie.geckolib3.geo.exception.GeckoLibException: doom:geo/motherdemon.geo.json: Could not find model. If you are getting this with a built mod, please just restart your game.
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:109)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:151)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.method_3936(GeoEntityRenderer.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1482)
	at net.minecraft.class_761.method_22710(class_761.java:1230)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.method_3192(class_757.java:810)
	at net.minecraft.class_310.method_1523(class_310.java:1112)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at software.bernie.geckolib3.model.AnimatedGeoModel.getModel(AnimatedGeoModel.java:109)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.render(GeoEntityRenderer.java:151)
	at software.bernie.geckolib3.renderers.geo.GeoEntityRenderer.method_3936(GeoEntityRenderer.java:41)

-- Entity being rendered --
Details:
	Entity Type: doom:motherdemon (mod.azure.doom.entity.tierboss.MotherDemonEntity)
	Entity ID: 3648
	Entity Name: Mother Demon
	Entity's Exact location: 144.02, 62.00, 54.03
	Entity's Block location: World: (144,62,54), Section: (at 0,14,6 in 9,3,3; chunk contains blocks 144,0,48 to 159,255,63), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.05, -0.08, -0.01
	Entity's Passengers: []
	Entity's Vehicle: null

-- Renderer details --
Details:
	Assigned renderer: mod.azure.doom.client.render.MotherDemonRender@13b9a675
	Location: 180.07,-3.62,122.45 - World: (180,-4,122), Section: (at 4,12,10 in 11,-1,7; chunk contains blocks 176,0,112 to 191,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -102.65625
	Delta: 0.8002912
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:135)
	at net.minecraft.class_761.method_22977(class_761.java:1482)
	at net.minecraft.class_761.method_22710(class_761.java:1230)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Affected level --
Details:
	All players: 1 total; [class_746['KJ_SARGENT'/276, l='ClientLevel', x=-36.03, y=64.00, z=-68.40]]
	Chunk stats: 1024, 625
	Level dimension: mining_dims:nethering_dim
	Level spawn location: World: (192,73,-176), Section: (at 0,9,0 in 12,4,-11; chunk contains blocks 192,0,-176 to 207,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 2779142 game time, 2739497 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 3
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman, dark_mode_with_glock-_Copy.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1167258176 bytes (1113 MiB) / 3514826752 bytes (3352 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot AzureDoom/AzureDoom-Doom-Mod#1 capacity (MB): 16384.00
	Memory slot AzureDoom/AzureDoom-Doom-Mod#1 clockSpeed (GHz): 2.13
	Memory slot AzureDoom/AzureDoom-Doom-Mod#1 type: DDR4
	Virtual memory max (MB): 37579.84
	Virtual memory used (MB): 24261.98
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 443.64
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		advancements-enlarger: Advancements Enlarger 0.2.4
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.0
		aqupd: Caracal mob 1.17-1.2.2
		architectury: Architectury 2.2.21
		bclib: BCLib 0.2.4
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterend: Better End 0.10.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.0
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1
		calio: Calio 1.0.2
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.0.1
		cardinal-components-base: Cardinal Components API (base) 3.0.1
		cardinal-components-block: Cardinal Components API (blocks) 3.0.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.1
		cardinal-components-entity: Cardinal Components API (entities) 3.0.1
		cardinal-components-item: Cardinal Components API (items) 3.0.1
		cardinal-components-level: Cardinal Components API (world saves) 3.0.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.1
		cardinal-components-util: Cardinal Components API (utilities) 3.0.1
		cardinal-components-world: Cardinal Components API (worlds) 3.0.1
		carpet: Carpet Mod 1.4.44
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.20.0+build.633
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		clumps: Clumps fabric-1.17.1-7.0.4
		coat: Coat 1.0.0-beta.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		croptopia: Croptopia 1.5.0
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customportalapi: Custom Portal Api 0.0.1-beta38-1.17
		doom: Doom Fabric 4.0.0-beta1
		dual_riders: DualRiders 1.0.5
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 3.0.12
		expandedstorage: Expanded Storage 7.0.0-alpha.33
		fabric: Fabric API 0.37.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57718
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446318
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.3+kotlin.1.5.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57718
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446318
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57718
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		gamemodeoverhaul: GamemodeOverhaul 1.1.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.9
		gobber2: Gobber2 2.4.32
		horseinfo: Horse Info 0.3.0-1.17
		illuminations: Illuminations 1.6.2
		inventoryprofilesnext: Inventory Profiles Next 0.8.4
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		java: OpenJDK 64-Bit Server VM 16
		kibe: Kibe 1.8-BETA+1.17
		ksrch: Keybind Search 1.0.0
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libblockattributes_core: LibBlockAttributes (Core) 0.8.17003
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.17003
		libblockattributes_items: LibBlockAttributes (Items) 0.8.17003
		lithium: Lithium 0.7.3
		logical_zoom: Logical Zoom 0.0.11
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.5
		mcdw: MC Dungeons Weapons 3.2.4
		megane: megane 5.1.1
		megane-base: megane-base 5.1.1
		megane-kibe: megane-kibe 5.1.1+1.7.2-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.1.1+0.9.0
		megane-runtime: megane-runtime 5.1.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.1.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.1.1+5.0.2-beta-build.38
		megane-vanilla: megane-vanilla 5.1.1+1.17.1
		minecraft: Minecraft 1.17.1
		mining_dims: Mining Dimensions 1.1.9
		modmenu: Mod Menu 2.0.3
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		nbtcrafting: NBT Crafting 2.0.19+mc1.17
		noanglebrackets: NoAngleBrackets 1.1.0
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		physicsmod: Physics Mod 2.3.3
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		ratsmischief: Rat's Mischief 1.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.4-beta+build.83
		reeses-sodium-options: Reese's Sodium Options 1.1.2
		repurposed_structures: Repurposed Structures 2.1.2+1.17.1
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		simple_backpack: SimpleBackpack 1.1.13
		sodium: Sodium 0.3.0+build.5
		sodium-extra: Sodium Extra 0.3.3
		spiceoffabric: Spice of Fabric 1.3.4+1.17.1
		spruceui: SpruceUI 3.2.0+1.17
		stoneholm: Stoneholm 1.3
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.4-beta+build.83
		the_bumblezone: The Bumblezone - Fabric 3.0.6+1.17.1
		trinkets: Trinkets 3.0.2
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		waystones: Waystones 2.0.2
		wthit: wthit 3.7.0
		yungsapi: YUNG's API 1.17-Fabric-13
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 2560x1377
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman, file/dark_mode_with_glock-_Copy.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor

**Comment by AzureDoom** [comment]
new beta released that fixes this and the other report of yours.
