### ISSUE TITLE
Serverside not working

### ISSUE THREAD

**Issue by Noaaan** [AzureDoom/AzureDoom-Doom-Fabric#3]
In latest version for 1.16.3 it does not work properly.
[crash.log](https://github.com/AzureDoom/AzureDoom-Doom-Fabric/files/5241675/crash.log)
One of my problems were the dependents of the mod. Not all of them are listed on CurseForge.
Works well in SinglePlayer, except the shield is bugged. Awesome mod, please make it work for servers!

**Comment by AzureDoom** [comment]
Good catch, I thought removed that lib for it not working. Fix out shortly

**Comment by AzureDoom** [comment]
Please try the latest I just pushed and let me know please!

**Comment by Noaaan** [comment]
Hello, it works now! Sorry for the late response.
