### ISSUE TITLE
1.16.3 Fabric - Mod causes CTD on startup.

### ISSUE THREAD

**Issue by matty45** [AzureDoom/AzureDoom-Doom-Fabric#8]
Here is the log: https://paste.ee/p/ApBGQ

Here is another log with curios api added: https://paste.ee/p/QjOwp

Are there any dependencies that you forgot to mention somewhere? I cannot find them on the main download page.

**Comment by matty45** [comment]
You should probably put that requirement in the mods description when you have the chance.

**Comment by AzureDoom** [comment]
The whole page will get a revamp when the new mobs are done so always look at the file itself.

**Comment by matty45** [comment]
Ok, thanks for the quick responce btw!
