### ISSUE TITLE
Mod incompatible with Sodium

### ISSUE THREAD

**Issue by matty45** [AzureDoom/AzureDoom-Doom-Fabric#9]
Here is the log: https://paste.ee/p/cnbpi

**Comment by AzureDoom** [comment]
This is a Geckolib issue not my mod, I don't use Sodium myself and given they both mess with Rendering I don't believe they'd be compatible. I suggest making an issue with both Sodium and Geckolib and link the issues.

**Comment by matty45** [comment]
Ok, thanks again.
